/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Get file description
 #	author : miyako
 #	2018/05/15
 #
 # --------------------------------------------------------------------------------*/



// --- Get file description
void Get_file_description(sLONG_PTR *pResult, PackagePtr pParams);
