/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Get-file-description.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Get file description
 #	author : miyako
 #	2019/12/12
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Get-file-description.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Get file description
            
			case 1 :
				Get_file_description(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void Get_file_description(PA_PluginParameters params) {

    sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
    PackagePtr pParams = (PackagePtr)params->fParameters;
    
        C_TEXT Param1;
        C_TEXT returnValue;

        Param1.fromParamAtIndex(pParams, 1);

    #if VERSIONWIN
        SHFILEINFO fileinfo;

        if (SHGetFileInfo((LPCTSTR)Param1.getUTF16StringPtr(),
            FILE_ATTRIBUTE_NORMAL,
            &fileinfo,
            sizeof(fileinfo),
            SHGFI_TYPENAME | SHGFI_USEFILEATTRIBUTES))
        {
            returnValue.setUTF16String((const PA_Unichar *)fileinfo.szTypeName, wcslen(fileinfo.szTypeName));
        }
    #else
        NSString *fileName = Param1.copyUTF16String();
        NSString *extension = [fileName pathExtension];
        
        /* patch for iWorks types */
        if([[extension lowercaseString]isEqualToString:@"key"])
        {
            returnValue.setUTF16String([[NSWorkspace sharedWorkspace]localizedDescriptionForType:@"com.apple.iwork.keynote.sffkey"]);
            goto end;
        }
        
        if([[extension lowercaseString]isEqualToString:@"pages"])
        {
            returnValue.setUTF16String([[NSWorkspace sharedWorkspace]localizedDescriptionForType:@"com.apple.iwork.pages.sffpages"]);
            goto end;
        }

        if([[extension lowercaseString]isEqualToString:@"numbers"])
        {
            returnValue.setUTF16String([[NSWorkspace sharedWorkspace]localizedDescriptionForType:@"com.apple.iwork.numbers.sffnumbers"]);
            goto end;
        }
        /* end of patch */
        else
        {
            NSString *uti = (NSString *)UTTypeCreatePreferredIdentifierForTag(kUTTagClassFilenameExtension, (CFStringRef)extension, NULL);
            if(uti)
            {
                returnValue.setUTF16String([[NSWorkspace sharedWorkspace]localizedDescriptionForType:uti]);
                [uti release];
            }
        }

    end:

        [fileName release];
    #endif

        returnValue.setReturn(pResult);

}

