/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Get-file-description.h
 #	source generated by 4D Plugin Wizard
 #	Project : Get file description
 #	author : miyako
 #	2019/12/12
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_GET_FILE_DESCRIPTION_H
#define PLUGIN_GET_FILE_DESCRIPTION_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"

#pragma mark -

void Get_file_description(PA_PluginParameters params);

#endif /* PLUGIN_GET_FILE_DESCRIPTION_H */
